# Generated by Django 3.2.14 on 2022-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='galleryreview',
            constraint=models.UniqueConstraint(fields=('gallery', 'user'), name='unique_gallery_user_review'),
        ),
        migrations.AddConstraint(
            model_name='journalreview',
            constraint=models.UniqueConstraint(fields=('journal', 'user'), name='unique_journal_user_review'),
        ),
        migrations.AddConstraint(
            model_name='newreview',
            constraint=models.UniqueConstraint(fields=('new', 'user'), name='unique_new_user_review'),
        ),
    ]
