# Generated by Django 3.2.14 on 2022-09-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220923_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreview',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newreviews', to='api.new', verbose_name='новость'),
        ),
    ]
