# Generated by Django 3.2.14 on 2022-09-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_newreview_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryreview',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryreviews', to='api.gallery', verbose_name='журнал'),
        ),
        migrations.AlterField(
            model_name='journalreview',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalreviews', to='api.journal', verbose_name='журнал'),
        ),
    ]
