# Generated by Django 3.2.14 on 2022-09-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220923_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='new',
            name='rating',
        ),
    ]
