# Generated by Django 3.2.14 on 2022-09-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220923_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalreview',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.journal', verbose_name='журнал'),
        ),
    ]
