# Generated by Django 3.2.14 on 2022-09-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_journalreview_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryreview',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.gallery', verbose_name='журнал'),
        ),
    ]
