# Generated by Django 3.2.14 on 2022-09-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_galleryreview_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreview',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.new', verbose_name='новость'),
        ),
    ]
